FROM ubuntu:14.04

ENV NSJAIL_VERSION=ba01ae76f2f7acc4e09ffa9a60315824aa8ca088

# AOSP dependencies from https://source.android.com/setup/initializing
RUN apt-get update && \

    # AOSP dependencies from https://source.android.com/setup/initializing
    apt-get install -y \
      bison \
      build-essential \
      ccache \
      curl \
      flex \
      g++-multilib \
      gcc-multilib \
      git-core \
      gnupg \
      gperf \
      lib32ncurses5-dev \
      lib32z-dev \
      libc6-dev-i386 \
      libgl1-mesa-dev \
      libx11-dev \
      libxml2-utils \
      unzip \
      x11proto-core-dev \
      xsltproc \
      zip \
      zlib1g-dev \

      # Additional googleplex master dependencies in go/howdoiandroid
      liblz4-tool \

      # Qualcomm specific dependencies
      # Required to build the kernel:
      #   bc for /usr/bin/bc
      #   libssl-dev for /usr/include/openssl
      # Required to build OTA package:
      #   openssl for /usr/bin/openssl
      #   bsdmainutils for /usr/bin/hexdump
      # Required to build msm8937_32go:
      #   genisoimage for /usr/bin/mkisofs
      # Required to build QSaharaServer:
      #   cmake
      bc \
      bsdmainutils \
      cmake \
      genisoimage \
      libssl-dev \
      libxml-simple-perl \
      openssl \

      # Android requires python2.7
      # TODO(diegowilson): why didn't this come with the default trusty build?
      python2.7 \

      # Install NsJail dependencies
      autoconf \
      bison \
      flex \
      gcc \
      g++ \
      git \
      libprotobuf-dev \
      libtool \
      make \
      pkg-config \
      protobuf-compiler \

      # Use pigz to speed up archive operations
      pigz \
      && \

    # Clean up APT cache as suggested in
    # https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get
    rm -rf /var/lib/apt/lists/* && \

    # Add missing python symbolic links
    # TODO(diegowilson): investigate the right way to setup python defaults
    ln --symbolic /usr/bin/python2.7 /usr/bin/python && \
    ln --symbolic /usr/bin/python2.7 /usr/bin/python2 && \

    # Install NsJail
    git clone https://github.com/google/nsjail.git && \
    git -C nsjail checkout $NSJAIL_VERSION && \
    make --directory=nsjail && \
    mv nsjail/nsjail /bin && \
    rm -rf nsjail && \

    # Install repo as instructed in
    # https://source.android.com/setup/downloading#installing-repo
    curl https://storage.googleapis.com/git-repo-downloads/repo > \
      /usr/bin/repo && \
    chmod a+rx /usr/bin/repo

# This COPY command almost vestigial. Nsjail now gets its configuration from
# the mounted source tree (which means we can change the jail configuration
# without having to regen the docker image). However, there may still be some
# branches that depend on injecting the config into the container, so we can't
# delete this line yet.
COPY nsjail.cfg /usr/share/android-build.cfg

RUN chmod a+r /usr/share/android-build.cfg

COPY etc/sudoers.d/android-build /etc/sudoers.d/android-build
